stages:
  - prepare
  - lint
  - test
  - build
  - e2e

variables:
  NODE_VERSION: '16.14.0' # ou la version que vous utilisez

prepare:
  stage: prepare
  image: node:$NODE_VERSION
  script:
    - npm install
  only:
    - /^feat\/.*$/

before_script:
  - npm install -g pnpm # Install pnpm globaly

lint:
  stage: lint
  image: node:$NODE_VERSION
  script:
    - pnpm install
    - npx nx lint workspace-ui
  only:
    - /^feat\/.*$/

test:
  stage: test
  image: node:$NODE_VERSION
  script:
    - pnpm install
    - npx nx test workspace-ui
  only:
    - /^feat\/.*$/

build:
  stage: build
  image: node:$NODE_VERSION
  script:
    - pnpm install
    - npx nx build workspace-ui
  only:
    - /^feat\/.*$/
    
e2e:
  stage: e2e
  image: cypress/browsers:latest
  cache:
    paths:
      - node_modules/
      - /root/.cache/Cypress
  script:
    - pnpm install
    - npx nx serve workspace-ui --port=4200 & # Lance le serveur en arrière-plan
    - sleep 30 # Attend que le serveur soit opérationnel
    - cd apps/workspace-ui-e2e
    - npx cypress install
    - npx cypress run --config-file cypress.config.ts
  only:
    - /^feat\/.*$/