FROM node:18.17.1-bookworm

LABEL org.openrichmedia="The Open Rich Media Initiative"
LABEL name="reg.docker.openrichmedia.org:agamis.workspace.node18lts-0923-dev"
LABEL version="1.0"
LABEL description="An image for dev environment packed with Node 18.17 and PNPM"

# install PNPM
ENV SHELL=/bin/bash
RUN curl -fsSL https://get.pnpm.io/install.sh | sh -
